name: Build studio and ingress

on:
  push:
    branches:
      - main
      - staging

  release:
    types: [published]

jobs:

  build-containers:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}