name: Build studio and ingress

on:
  push:
    branches:
      - main
      - staging

  release:
    types: [published]

jobs:
  build-containers:
    if: github.repository == 'sandstromviktor/semver'
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
    - name: Log in to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest tag
      id: latest_tag
      run: |
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo ::set-output name=tag::$TAG

    - name: docker build ingress
      uses: docker/build-push-action@v2
      with:
        context: .
        push: "${{ github.event_name != 'pull_request' }}"
        tags: ghcr.io/${{ github.repository }}:${{ steps.latest_tag.outputs.tag }}
        file: Dockerfile
