name: Build studio and ingress

on:
  push:
    branches:
      - main
      - staging

  release:
    types: [published]

jobs:
  build-containers:
    if: github.repository == 'sandstromviktor/semver'
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
    - name: Log in to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ghcr.io/${{ github.repository }}
    - name: docker build ingress
      uses: docker/build-push-action@v2
      with:
        context: .
        push: "${{ github.event_name != 'pull_request' }}"
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: Dockerfile
