name: Build studio and ingress

on:
  push:
    branches:
      - main
      - staging
    tags:
      - 'v*'

  release:
    types: [published]

jobs:
  build-containers:
    if: github.repository == 'sandstromviktor/semver'
    runs-on: ubuntu-20.04
    strategy:
        fail-fast: false
        matrix:
          include:
            - dockerfile: ./Dockerfile
              image: ghcr.io/${{ github.repository }}/image1
            - dockerfile: ./Dockerfile.nginx
              image: ghcr.io/${{ github.repository }}/image2
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2  

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value={{date 'YYYYMMDD'}},prefix=${{ github.ref_name }}-
            type=semver,pattern={{version}}

      - name: Log in to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: "${{ github.event_name != 'pull_request' }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ matrix.dockerfile }}
